# Generated by Django 5.1.6 on 2025-05-15 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('form_level', models.CharField(choices=[('Form 1', 'Form 1'), ('Form 2', 'Form 2')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('form_level', models.CharField(choices=[('Form 1', 'Form 1'), ('Form 2', 'Form 2')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50)),
                ('ic_number', models.CharField(max_length=14, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('race', models.CharField(choices=[('Malay', 'Malay'), ('Chinese', 'Chinese'), ('Indian', 'Indian'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('intake', models.CharField(choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=10)),
                ('number_matric_std', models.CharField(blank=True, max_length=20, unique=True)),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_contact', models.CharField(max_length=20)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.classroom')),
                ('subjects', models.ManyToManyField(to='myApp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(choices=[('Malay', 'Malay'), ('Chinese', 'Chinese'), ('Indian', 'Indian'), ('Other', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('ic_number', models.CharField(max_length=14, unique=True)),
                ('age', models.IntegerField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teacher_profiles/')),
                ('intake', models.CharField(choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=10)),
                ('number_matric_teach', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('assigned_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.classroom')),
                ('subjects', models.ManyToManyField(to='myApp.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_students', to='myApp.teacher'),
        ),
        migrations.CreateModel(
            name='StudentPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(choices=[('U', 'Urban'), ('R', 'Rural')], max_length=1)),
                ('famsize', models.CharField(choices=[('B40', 'B40'), ('M40', 'M40'), ('T20', 'T20')], max_length=3)),
                ('pstatus', models.CharField(choices=[('T', 'Together'), ('A', 'Apart')], max_length=1)),
                ('medu', models.IntegerField()),
                ('fedu', models.IntegerField()),
                ('mjob', models.CharField(choices=[('teacher', 'Teacher'), ('admin', 'Administrative'), ('police', 'Police'), ('housewife', 'Housewife'), ('other', 'Other')], max_length=20)),
                ('fjob', models.CharField(choices=[('teacher', 'Teacher'), ('admin', 'Administrative'), ('police', 'Police'), ('househusband', 'Househusband'), ('other', 'Other')], max_length=20)),
                ('guardian', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('other', 'Other')], max_length=10)),
                ('traveltime', models.IntegerField()),
                ('studytime', models.IntegerField()),
                ('merit', models.IntegerField()),
                ('famsup', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('activities', models.IntegerField()),
                ('internet', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('famrel', models.IntegerField()),
                ('freetime', models.IntegerField()),
                ('goout', models.IntegerField()),
                ('health', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.student')),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.subject')),
            ],
            options={
                'unique_together': {('student', 'subject', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('R', 'Reason (Excused)')], max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.student')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.teacher')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
