# Generated by Django 5.1.6 on 2025-05-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='form_level',
            field=models.CharField(blank=True, choices=[('Form 1', 'Form 1'), ('Form 2', 'Form 2')], max_length=10, null=True),
        ),
    ]
