# Generated by Django 5.1.6 on 2025-05-19 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_parentprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpersonal',
            name='activities',
            field=models.IntegerField(help_text='0 = None, 1 = 1–2, 2 = 2–3, 3 = 4–5, 4 = 5+', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='studentpersonal',
            name='famrel',
            field=models.IntegerField(help_text='1 = Very poor, 5 = Excellent', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='studentpersonal',
            name='fedu',
            field=models.IntegerField(help_text='1 = Primary, 7 = PhD', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='studentpersonal',
            name='freetime',
            field=models.IntegerField(help_text='1 = Very little, 5 = A lot', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='studentpersonal',
            name='goout',
            field=models.IntegerField(help_text='1 = Rarely, 5 = Very often', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='studentpersonal',
            name='health',
            field=models.IntegerField(help_text='1 = Poor, 5 = Excellent', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='studentpersonal',
            name='internet',
            field=models.IntegerField(help_text='0 = None, 1 = 1–2hrs, 2 = 3–4hrs, 3 = 4–5hrs, 4 = 5+hrs', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='studentpersonal',
            name='medu',
            field=models.IntegerField(help_text='1 = Primary, 7 = PhD', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='studentpersonal',
            name='merit',
            field=models.IntegerField(help_text='0 = None, 1 = 1–3, 2 = 3–5, 3 = 5+', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='studentpersonal',
            name='studytime',
            field=models.IntegerField(help_text='1 = 1hr, 2 = 2–3hrs, 3 = 4–5hrs, 4 = 5hrs+', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='studentpersonal',
            name='traveltime',
            field=models.IntegerField(help_text='1 = <10min, 2 = 10–15min, 3 = 20–25min, 4 = 30min+', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
