# Generated by Django 5.1.6 on 2025-05-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_studentpersonal_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateField(default='2017-02-12'),
            preserve_default=False,
        ),
    ]
